mode: LOBBY
settings:
  plugin-name-key: nivorabedwars
queue:
  task-name: Bedwars
  min-players: 2
  max-players: 16
  tick-interval-ticks: 20
  service-reservation-seconds: 20
  map-rotation:
    - bw_map1
    - bw_map2
    - bw_map3
lobby:
  join-item:
    enabled: false
    material: COMPASS
    slot: 4
    name: "&7Bedwars spielen"
    lore:
      - "&7Klicke, um der Queue beizutreten"
cloudnet:
  static-only: true
  static-services:
    - Bedwars-1-1
    - Bedwars-2-1
    - Bedwars-3-1
  service-map-assignments:
    Bedwars-1-1: bw_map1
    Bedwars-2-1: bw_map2
    Bedwars-3-1: bw_map3
  fallback-service: Lobby-1
  commands:
    start: ""
    connect: ""
game:
  service-name: "Lobby-1"
  arena-maps: []
  map-id: bw_map1
  start-countdown-seconds: 10
  respawn-delay-seconds: 5
  reset-delay-seconds: 10
  disable-hunger: true
  block-item-drops: true
  friendly-fire: false
  allow-damage-in-waiting: false
# maps: Auf der Lobby optional nicht noetig; kann aber identisch zu den GAME-Servern bleiben.

